### ISSUE TITLE
throw error if there is no bluetooth hardware present on host machine

### ISSUE THREAD

**Issue by VikramTiwari** [PolymerElements/platinum-bluetooth#13]
So today in Ubiquity conference, I was trying this [codelab](https://codelabs.developers.google.com/codelabs/polymer-bluetooth/index.html?). Ended up debugging for 15 minutes before I found out that there was no bluetooth device on the host machine. :stuck_out_tongue_closed_eyes:

**Comment by beaufortfrancois** [comment]
May I ask which host machine you had? 
I believe there were some Chromebooks available at the Ubiquity Conference.

**Comment by beaufortfrancois** [comment]
Moreover, you should have seen a ""Bluetooth adapter not available."" error according to https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/bluetooth/bluetooth_dispatcher_host.cc&rcl=1452659659&l=646

**Comment by VikramTiwari** [comment]
Not sure, but the interface was OS-X based, so assuming Mac Mini, but even they have bluetooth hardware as I see in specs.

Tried the same codelab on my mac air with a bluetooth keyboard and trackpad attached, and got following error. 

![screen shot 2016-01-13 at 9 40 09 am](https://cloud.githubusercontent.com/assets/1330677/12302378/bad576a6-b9d9-11e5-8ee9-723b40fe7f3d.png)

This is the same error I was getting at the event. And while debugging on the machine, and checking in system preferences, found that there was no bluetooth peripheral. But now since I am getting the same on my machine, seems something else is wrong her.

**Comment by jyasskin** [comment]
We don't support Mac well yet, and the codelab does say a "Chromebook or an Android M Device" is a prerequisite, but we should also give good error messages instead of just cancelling the chooser. We have https://crbug.com/529547 to track giving that error.

**Comment by VikramTiwari** [comment]
Ah! Thanks for the link @jyasskin. Will keep an eye on it. :+1: Closing this.
