### ISSUE TITLE
Subscribe to notifications from BLE device?

### ISSUE THREAD

**Issue by ketile** [PolymerElements/platinum-bluetooth#14]
Can't find any documentation on subscribing and unsubscribing to notifications using platinum-bluetooth. Is this possible or planned for implementation? Have not yet tried with the vanilla Web Bluetooth API but it [seems possible](https://github.com/WebBluetoothCG/web-bluetooth/search?q=startNotifications&type=Issues&utf8=%E2%9C%93).

Need this functionality for a demo and wondering if I should use Web Bluetooth API directly or through Polymer.

**Comment by beaufortfrancois** [comment]
It is not yet implemented in `platinum-bluetooth`.
I'm waiting for notifications to land in stable channel to update `platinum-bluetooth`.

You may want to use Web Bluetooth API instead for the moment and make sure you use a recent Chromium build on Android (https://download-chromium.appspot.com/?platform=Android).

See https://googlechrome.github.io/samples/web-bluetooth/notifications.html for how it works.

**Comment by jyasskin** [comment]
You should be able to combine the Polymer elements with the lower-level JS API. Right now, the `BluetoothGATTCharacteristic` you need is only exposed as `<bluetooth-gatt-characteristic>._characteristic`, but I think we should make that public so folks can fill in holes like this.

**Comment by beaufortfrancois** [comment]
Fixed with https://github.com/PolymerElements/platinum-bluetooth/commit/18a1c063ac4f0d82bb500eecc5b6ac2df64ffef9

**Comment by beaufortfrancois** [comment]
@ketile You can give it a try now with WIP https://github.com/PolymerElements/platinum-bluetooth/pull/15
