### ISSUE TITLE
building a webapp using polymer. What is the roadmap of this element to get in a cross platform browsers ? S

### ISSUE THREAD

**Issue by sowsan** [PolymerElements/platinum-bluetooth#18]
Since we are developing a WebApp and Bluetooth is one of the main feature that we need. It would be great if this feature available to all type of browsers. Thanks !

**Comment by beaufortfrancois** [comment]
You will find all updates about Chrome Implementation status at https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md#chrome.
Check out https://plus.google.com/communities/108953318610326025178 as well.

**Comment by sowsan** [comment]
Thank you !
