### ISSUE TITLE
Consistent version tags starting with a "v" platinum-bluetooth

### ISSUE THREAD

**Issue by bartolom** [PolymerElements/platinum-bluetooth#20]
### Description

This issue is very similar to https://github.com/PolymerElements/iron-ajax/issues/227 

Most PolymerElements github projects follow a very consistent naming pattern for the git tags that are used to mark releases. They always start with a "v" like `v1.2.3`

F.i.: Very consistent: https://github.com/PolymerElements/paper-input/releases

F.i. Less consistent: https://github.com/PolymerElements/iron-ajax/releases
F.i. Less consistent: https://github.com/PolymerElements/platinum-bluetooth/releases
in `platinum-bluetooth` there are sometime tags like `v2.0.0` and `2.1.1`

Being very consistent would allow other build tools on other platforms like Java/JVM to reason about the tags, and do smart things with the semantic versioning information. This would also allow easier use of https://webjars.org 

It would be nice when future release would be more consistent again.

### Expected outcome

https://github.com/PolymerElements/platinum-bluetooth/releases/tag/v2.1.1

### Actual outcome

https://github.com/PolymerElements/platinum-bluetooth/releases/tag/2.1.1

missing the `v` in front of `2.1.1` in the URL

### Browsers Affected
This does not affect browsers, but rather build tools like Maven/Gradle (on the JVM) that have custom code/plugin that try to reason about the semantic version

**Comment by beaufortfrancois** [comment]
Thank you @bartolom.
You're right, my bad. I've just fixed it at https://github.com/PolymerElements/platinum-bluetooth/releases/tag/v2.1.1
