### ISSUE TITLE
Daydream controller sender (emulator)

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [PolymerElements/platinum-bluetooth#31]
There is a Google Daydream controller receiver written in JavaScript using Web Bluetooth API: https://github.com/mrdoob/daydream-controller.js

Is it possible to write Daydream controller sender (emulator) completely in JavaScript using Web Bluetooth API and Motion Sensors APIs based on Generic Sensor API (https://www.chromestatus.com/feature/5698781827825664) that allows to use a device with relevant sensors (e.g. Android smartphone with gyroscope) in place of a Daydream controller?

If yes, is it possible to do that using `<platinum-bluetooth>` elements?

Now I'm using native Daydream controller emulator Android app: https://developers.google.com/vr/daydream/controller-emulator.

**Comment by FluorescentHallucinogen** [comment]
@beaufortfrancois PTAL.

**Comment by beaufortfrancois** [comment]
It is not possible sadly yet to write this emulator in JavaScript using Web Bluetooth as it only support GATT Client role for now (not Server).
See https://github.com/WebBluetoothCG/web-bluetooth/issues/78
