### ISSUE TITLE
Add a new <platinum-bluetooth-service> element

### ISSUE THREAD

**Issue by beaufortfrancois** [PolymerElements/platinum-bluetooth#6]
Something like this below would help readibility.

```html
<platinum-bluetooth-device services-filter='["f000ffc0-0451-4000-b000-000000000000"]' id="plane-device">
  <platinum-bluetooth-service service="75b64e51-f181-4ed1-921a-476090d80ba7">
    <platinum-bluetooth-characteristic id="engineCharacteristic"
      characteristic="75b64e51-f184-4ed1-921a-476090d80ba7"
      auto-write>
    </platinum-bluetooth-characteristic>
    <platinum-bluetooth-characteristic id="rudderCharacteristic"
      characteristic="75b64e51-f185-4ed1-921a-476090d80ba7"
      auto-write>
    </platinum-bluetooth-characteristic>
  </platinum-bluetooth-service>
</platinum-bluetooth-device>
```

**Comment by ketile** [comment]
This is helpful in my opinion. Currently working on a project with many characteristics belonging to the same service and this is easier to both read and write.

**Comment by beaufortfrancois** [comment]
I will add this new element for sure in the next version.

**Comment by beaufortfrancois** [comment]
For info, I've started coding next version at https://github.com/PolymerElements/platinum-bluetooth/compare/v2?expand=1

**Comment by beaufortfrancois** [comment]
Fixed with https://github.com/PolymerElements/platinum-bluetooth/commit/966dd981bb4b765c621dbfc85fde1a0db83f1913

**Comment by beaufortfrancois** [comment]
@ketile You can give it a try now by checking out WIP https://github.com/PolymerElements/platinum-bluetooth/pull/15

**Comment by ketile** [comment]
@beaufortfrancois Great!
